import pandas as pd

examples = pd.read_csv(r'.\data\few_shot_examples.csv').to_dict(orient="records")

documentation = [
    "our business defines a cycle as going from a state = 35 to the next state = 35, so like this 35,36,37,...,34,35",
    "our business considers a part has been manufactured in table 10 if a state=35 but in table 07 and table 03 its if state=30 has been registered in table_states",
    "our business considers production in table 10 to be perfect if its 22 parts a day, acceptable if its 20 or 21 parts a day and not acceptable for anything below 20",
    "our business only works from 8AM to 17PM.",
    "Column: Crit. tri (VARCHAR(50)), Description: Vehicle classification code used to filter automotive parts. Standard value is '000VEH0' for vehicle components., Business Purpose: Categorizes products by type (vehicle, spare parts, etc.), Sample Values: 000VEH0, Synonyms: classification code, sorting criteria, product type, vehicle code, part category",
    "Column: Article (VARCHAR(100)), Description: Main product or assembly identifier representing the top-level component in the manufacturing hierarchy., Business Purpose: Primary reference for finished products or major assemblies, Sample Values: M0BJI---N01, Synonyms: product code, assembly code, main part, parent component, finished product, assembly reference",
    "Column: Numéro d'article (VARCHAR(100)) - Project Name, Description: Project name or program identifier that groups related components under a common development initiative., Business Purpose: Links manufacturing data to specific automotive programs or product lines, Sample Values: Projet XJI---, Synonyms: project name, program name, project code, development program, product program, project identifier",
    "Column: Anc. n° article (VARCHAR(100)) - Delivery Site, Description: Manufacturing or delivery site where the component will be produced or shipped., Business Purpose: Identifies production location for logistics and planning, Sample Values: PITESTI, Synonyms: delivery site, production site, manufacturing location, plant location, facility, factory site, production center",
    "Column: Composant (VARCHAR(100)), Description: Individual component or sub-assembly part number within the product structure., Business Purpose: Identifies specific parts that need to be manufactured or assembled, Sample Values: M000517D02B, M100512D01, Synonyms: component, part number, sub-assembly, child component, manufactured part, component reference",
    "Column: Qté Composant (FLOAT), Description: Quantity of each component required per parent assembly or finished product., Business Purpose: Defines material requirements and quantities for production planning, Sample Values: 1.0, Synonyms: component quantity, required quantity, parts quantity, assembly quantity, usage quantity, BOM quantity",
    "Column: Art.intra-process (VARCHAR(100)), Description: Work-in-progress part number representing the component during manufacturing stages before completion., Business Purpose: Tracks parts through manufacturing process stages, Sample Values: M000517D02B, M000517D02, M100512D01, Synonyms: WIP part, in-process part, manufacturing part, work-in-progress, intermediate part, process part",
    "Column: Article1 (VARCHAR(100)) - Parts We Manufacture, Description: Reference number for parts that are manufactured in-house, representing components produced by the company., Business Purpose: Identifies which parts are manufactured internally vs purchased externally, Sample Values: M000517D02B, M000517D02, M100512D01, Synonyms: manufactured part, internal part, production part, make part, in-house component, fabricated part",
    "Column: Opé. (VARCHAR(50)), Description: Sequential operation number indicating the manufacturing step sequence in the production process., Business Purpose: Defines the order and sequence of manufacturing operations, Sample Values: 10.0, 1500.0, 2000.0, Synonyms: operation number, step number, process step, manufacturing step, operation sequence, process sequence",
    "Column: Description (TEXT), Description: Detailed description of the manufacturing operation or process being performed., Business Purpose: Explains what work is being done at each manufacturing step, Sample Values: SOUDURE 7 PSR+MARQUAGE TRAÇABILITE, DECOUPE OAS (D & G), RECONDITIONNEMENT, Synonyms: operation description, process description, work description, task description, manufacturing process, operation details",
    "Column: Pos.trav (VARCHAR(50)), Description: Work station or manufacturing cell identifier where the operation is performed., Business Purpose: Identifies physical location and equipment for capacity planning, Sample Values: ILT_SR04, PA0400_3, RECOND, CTRLSynonyms: work position, workstation, manufacturing cell, work center, production station, machine station",
    "Column: NbrPer (FLOAT), Description: Number of operators or personnel required to perform the manufacturing operation., Business Purpose: Determines labor requirements and staffing needs, Sample Values: 1.0, 2.0, Synonyms: number of operators, personnel count, worker count, staff required, labor requirement, operator requirement",
    "Column: Cadence (FLOAT), Description: Production rate or speed, typically measured in parts per hour or cycle time., Business Purpose: Defines manufacturing speed capability for capacity calculations, Sample Values: 162.0, 200.0, 400.0, 2640.0, 2700.0, Synonyms: production rate, cycle rate, manufacturing speed, throughput, parts per hour, production speed",
    "Column: Emp.Pce (FLOAT), Description: Number of parts or pieces produced in each machine cycle or operation cycle., Business Purpose: Determines output quantity per cycle for capacity calculations, Sample Values: 1.0, 2.0, Synonyms: parts per cycle, pieces per cycle, output per cycle, parts per operation, cycle output",
    "Column: Emp.Moule (FLOAT), Description: Number of molds, dies, or fixtures used simultaneously in each production cycle., Business Purpose: Indicates tooling capacity and parallel production capability, Sample Values: 1.0, 2.0, Synonyms: molds per cycle, dies per cycle, fixtures per cycle, tooling count, mold count",
    "Column: Désignation (TEXT), Description: Technical designation or name of the equipment, machine, or manufacturing resource used., Business Purpose: Identifies specific equipment for maintenance and capacity planning, Sample Values: Robot Soudure par Point_Pince X LONG, Presse Auto 0400T - TAC AIDA, Synonyms: equipment name, machine designation, equipment type, machine name, resource designation",
    "Column: TRS % (FLOAT), Description: Overall Equipment Effectiveness percentage, combining availability, performance, and quality metrics., Business Purpose: Measures manufacturing efficiency and equipment utilization, Sample Values: 0.0, 68.0, 80.0, Synonyms: OEE, equipment effectiveness, machine efficiency, utilization rate, performance rate, efficiency percentage",
    "Column: Clé (VARCHAR(50)), Description: Key identifier or reference code linking operations to specific manufacturing areas or zones., Business Purpose: Groups operations by manufacturing area for organization and analysis, Sample Values: ZP01, ZP40, ZP41, Synonyms: key code, zone code, area code, reference key, operation key",
    "Column: Tool (VARCHAR(100)), Description: Specific tool, fixture, or equipment identifier used in the manufacturing operation., Business Purpose: Identifies tooling requirements for production planning and maintenance, Sample Values: MSR1131, MSR1132, MD00512, MD00515, Synonyms: tool ID, fixture, equipment ID, tooling reference, manufacturing tool",
    "Column: N° REN (VARCHAR(50)), Description: Tool reference or registration number used for tracking and identification purposes., Business Purpose: Provides traceable reference for tool management and maintenance, Sample Values: REN18-307, REN18-412, REN18-309, Synonyms: tool reference, REN number, tool registration, reference number, tool tracking number",
    "Column: DESIGN OUT (TEXT), Description: Technical specification or design description of the tool, including special requirements., Business Purpose: Provides detailed tool specifications and identifies special tooling needs, Sample Values: MDS RSR Face_A REN18-307, OUTIL OAS REN18-412, Synonyms: tool specification, design specification, tool description, technical specification, tooling details",
    "Column: Is_Masque (BOOLEAN), Description: Boolean flag indicating whether the operation requires protective masking or covering., Business Purpose: Identifies operations with special safety or quality requirements, Sample Values: FALSE, TRUE, Synonyms: masking required, mask flag, protection required, masking indicator, safety requirement",
    "Column: Category (INTEGER), Description: Numerical category grouping operations with similar characteristics for analysis purposes., Business Purpose: Groups similar operations across different parts for comparative analysis, Sample Values: 4725, 4728, 4731, 4752, 4755, Synonyms: operation category, group number, classification number, analysis group, operation group",
    "Column: Nbre outil par gamme (INTEGER), Description: Total number of tools required for the complete operation sequence or manufacturing route., Business Purpose: Indicates tooling complexity and resource requirements, Sample Values: 1, 2, Synonyms: tools per route, tooling count, tools required, tool quantity, tooling requirement",
    "Column: Volume (INTEGER), Description: Required production quantity or volume to be manufactured for the specified period., Business Purpose: Defines production targets for capacity and resource planning, Sample Values: 99, 199, Synonyms: production volume, quantity required, production quantity, manufacturing volume, target volume",
    "Column: Period (DATETIME), Description: Time period or date for which the production volume and planning data applies from table charge_capa3., Business Purpose: Provides temporal context for production planning and scheduling in table charge_capa3, Sample Values: 01/01/2025, Synonyms: production period, planning period, time period, production date, planning date",
    "Column: ZAP (VARCHAR(100)), Description: Manufacturing zone, area, or production unit designation where operations are performed., Business Purpose: Organizes operations by physical manufacturing areas for workflow management, Sample Values: ZAP Recond, ZAP CELLULE SR, ZAP FDL, ZAP MT, Synonyms: manufacturing zone, production area, work area, manufacturing unit, production zone",
    "Column: Nbre de PDC (FLOAT), Description: Number of production centers or manufacturing units available for the operation., Business Purpose: Indicates parallel production capacity and resource availability, Sample Values: 1.0, 8.0, Synonyms: production centers, manufacturing units, production lines, parallel capacity, resource count",
    "Column: TRS (FLOAT), Description: Actual TRS (Overall Equipment Effectiveness) value expressed as a decimal (0-1 scale) in table charge_capa3., Business Purpose: Represents real manufacturing efficiency for accurate time calculations in table charge_capa3, Sample Values: 0.68, 0.8, 1.0, Synonyms: actual OEE, real efficiency, effective rate, actual performance, true efficiency",
    "Column: TPS MACHINE NET (FLOAT), Description: Net machine time required for pure production without considering efficiency losses. Units are in hours., Business Purpose: Represents theoretical minimum time needed for production, Sample Values: 0.04, 0.49, 0.5, 1.23, Synonyms: net machine time, pure production time, theoretical time, ideal machine time",
    "Column: TPS PERTES (FLOAT), Description: Time losses due to equipment inefficiency, downtime, and quality issues. Units are in hours., Business Purpose: Quantifies time lost due to manufacturing inefficiencies, Sample Values: 0.0, 0.02, 0.12, Synonyms: time losses, lost time, inefficiency time, downtime, waste time",
    "Column: TPS MACHINE TT (FLOAT), Description: Total machine time including all losses and inefficiencies for realistic planning. Units are in hours., Business Purpose: Provides realistic time estimates for capacity planning, Sample Values: 0.05, 0.06, 0.5, 0.62, 1.23, Synonyms: total machine time, actual machine time, real machine time, total time required",
    "Column: TPS MOD TT (FLOAT), Description: Total labor time required, calculated by multiplying machine time by number of operators. Units are in hours., Business Purpose: Determines total labor hours needed for workforce planning, Sample Values: 0.05, 0.06, 0.5, 1.23, 1.24, Synonyms: total labor time, total operator time, workforce time, personnel time, labor hours",
    "Column: TPS OUTIL (FLOAT), Description: Time allocation per individual tool when multiple tools are used in the operation. Units are in hours., Business Purpose: Distributes total time across available tooling for utilization analysis, Sample Values: 0.05, 0.06, 0.31, 0.5, 1.23, Synonyms: tool time, per-tool time, individual tool time, tool allocation time",
    "Column: Taux de charge outil (FLOAT), Description: Tool utilization rate as a percentage of total available working time (255 days × 3 shifts × 7 hours)., Business Purpose: Measures how intensively tools are used relative to maximum capacity, Sample Values: 0.0, Synonyms: tool utilization rate, tool load rate, tool capacity utilization, tool usage rate, utilization percentage",
    "Table: shift_capacity, Column: shift_number (INTEGER), Description: Identifier for the work shift (e.g., first, second, or third shift)., Business Purpose: Distinguishes capacity data across different work shifts for planning and analysis., Sample Values: 1, 2, 3, Synonyms: shift ID, work shift, shift identifier",
    "Table: shift_capacity, Column: Period (DATE), Description: The starting date of the period (typically monthly) for which the capacity is defined., Business Purpose: Specifies the time frame for which the shift capacity is applicable, allowing for time-based capacity planning., Sample Values: \"2025-01-01\", \"2025-02-01\", Synonyms: date, time frame, capacity date, planning period start",
    "Table: shift_capacity, Column: capacity (FLOAT), Description: Available production capacity in hours for a specific shift and period. The actual capacity is derived by dividing the stored value by 4., Business Purpose: Defines the total available production time (in hours) for a given shift during a specific period, used for production scheduling and load balancing. The reported value is 1/4th of the stored database figure and is comparable to TPS columns from charge_capa3., Sample Values (raw stored values): 733, 704, 1466, 2199 (adjusted sample values: 183.25, 176, 366.5, 549.75), Synonyms: shift capacity, available hours, production hours, hourly capacity, adjusted capacity"
]



logo_path = "https://i.ibb.co/FL3mpvWR/gmd-logo.png"

tmp_file_dir = "webApp/tmp/"

app_secret_key = b'_5#y2L"F4Q8z\n\xec]/'

chromadb_path = r"webApp\chromadb"


